### ISSUE TITLE
Use same variables as systemd

### ISSUE THREAD

**Issue by valpackett** [passcod/catflap#2]
Hi. Noticed this on my github feed, always nice to see socket activation related projects!

I made [soad](https://github.com/myfreeweb/soad), a little utility that launches a server with a socket but stops it after a period of inactivity. I used systemd-compatible variables in order to leverage all the existing integrations everywhere (see readme).

Systemd passes the *number of opened sockets* (descriptors starting with 3) as `LISTEN_FDS`, not the number of the descriptor. You should probably support doing that :)

**Comment by passcod** [comment]
I accept pull requests :) But I have no time to work on this at this point.

**Comment by passcod** [comment]
Yes. I have no time at the moment, but I figured catflap should actually support opening multiple ports, too. I'll outline an issue about that and get to it eventually.

**Comment by passcod** [comment]
Archiving this project in favour of systemfd.
