### ISSUE TITLE
Add support for `SO_REUSEADDR` socket address

### ISSUE THREAD

**Issue by cipriancraciun** [passcod/catflap#5]
By default, at least on Linux, if I start `catflap`, then kill it and start it again (within a few seconds), it fails with `Could not bind: EADDRINUSE: Address already in use`, although there isn't any process actually listening on that endpoint (as confirmed by `netstat`);  this is because the TCP/IP stack on Linux disallows the usage of the same endpoint for a time if any "delayed" packets might be received.

In order to allow the immediate restart of `catflap`, the `SO_REUSEADDR` socket address must be set when creating the socket.  (This would be perhaps useful by default given that `catflap` is mainly meant for development purposes.)

(If accepted I'm willing to provide the patch.)

**Comment by passcod** [comment]
Would merge a patch on this too! except may as well do it outright and don't even add an option to disable, unless there's a downside?

**Comment by cipriancraciun** [comment]
> [...] don't even add an option to disable, unless there's a downside?

To my knowledge there is no downside.  (In all tools I've written, and in all production servers, I always configure the `SO_REUSEADDR` option.)

----

However I think this option is not accessible on all operating systems.  How should I handle this?  (I could add that option only on Linux.)

**Comment by passcod** [comment]
Wherever it compiles, and if that's only linux then sure.
